#服务
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  #数据源
  datasource:
    #根据环境配置
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxx
    username: xxx
    password: xxx

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # sql监控
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: true
      web-stat-filter:
        #uri 监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        #session监控
        session-stat-enable: true
        profile-enable: true
      # Spring监控
      aop-patterns: jd.com.*
      #开启druid后台
      stat-view-servlet:
        login-password: admin
        login-username: admin
        enabled: true
        url-pattern: "/druid/*"
        #访问白名单
        allow: 127.0.0.1



mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true




