server:
  port: 10086
  servlet:
    context-path: /boot

debug: false


jasypt:
  encryptor:
    password: dev

spring:
  datasource:
    url: jdbc:mysql://47.93.248.168:3336/z_study_springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: ENC(vCz0KjpodRW9CHkDolA3lvbvXBdLCn/cKmyM7pVznPCJ1Wn7EmS95XIfow6G29Hl)
    password: ENC(vCz0KjpodRW9CHkDolA3lvbvXBdLCn/cKmyM7pVznPCJ1Wn7EmS95XIfow6G29Hl)


mybatis-plus:
  configuration:
  # 打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




